# Generated by Django 5.2.6 on 2026-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_orden_ordenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Número de unidades disponibles en inventario.'),
        ),
    ]
