# Generated by Django 5.2.6 on 2026-05-05 17:52
# Modificada manualmente para asignar códigos únicos a productos existentes.

from django.db import migrations, models
from django.utils import timezone


def asignar_codigos_existentes(apps, schema_editor):
    """
    Asigna un código G-ddmmaahhN a todos los productos que aún no tienen uno.
    Usa la fecha/hora del campo 'creado' del producto para respetar
    la semántica del formato.
    """
    Producto = apps.get_model('catalogo', 'Producto')
    codigos_usados = set()

    # Procesar en orden de creación para que los consecutivos sean correctos
    for producto in Producto.objects.order_by('creado'):
        # Calcular prefijo basado en la fecha/hora de creación del producto
        ts     = timezone.localtime(producto.creado)
        prefix = f"G-{ts.strftime('%d%m%y%H')}"

        # Encontrar el próximo consecutivo libre
        n = 1
        while True:
            codigo = f"{prefix}{n}"
            if codigo not in codigos_usados:
                break
            n += 1

        producto.codigo = codigo
        producto.save(update_fields=['codigo'])
        codigos_usados.add(codigo)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_stock'),
    ]

    operations = [
        # Paso 1: añadir el campo SIN la restricción unique (permite blancos temporales)
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Generado automáticamente. Formato: G-ddmmaahhN',
                max_length=20,
                verbose_name='Código de producto',
            ),
        ),
        # Paso 2: poblar los productos existentes con códigos únicos
        migrations.RunPython(asignar_codigos_existentes, migrations.RunPython.noop),
        # Paso 3: ahora sí aplicar la restricción unique de forma segura
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Generado automáticamente. Formato: G-ddmmaahhN',
                max_length=20,
                unique=True,
                verbose_name='Código de producto',
            ),
        ),
    ]
