# Generated by Django 5.2.6 on 2026-05-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle y número'),
        ),
        migrations.AddField(
            model_name='orden',
            name='ciudad',
            field=models.CharField(blank=True, default='Mérida', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='orden',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='orden',
            name='estado_mx',
            field=models.CharField(blank=True, default='Yucatán', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(blank=True, default='card', max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='referencias',
            field=models.TextField(blank=True, help_text='Ej: casa azul, junto al OXXO, portón negro', verbose_name='Referencias de entrega'),
        ),
        migrations.AddField(
            model_name='orden',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Stripe PaymentIntent ID'),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto'),
        ),
    ]
