# Generated by Django 5.2.6 on 2026-05-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_orden_direccion_stripe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='Mi Casa', max_length=50, verbose_name='Alias de la dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle y número')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(default='Mérida', max_length=100, verbose_name='Ciudad')),
                ('estado_mx', models.CharField(default='Yucatán', max_length=50, verbose_name='Estado')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código postal')),
                ('referencias', models.TextField(blank=True, verbose_name='Referencias de entrega')),
                ('predetermina', models.BooleanField(default=False, verbose_name='Dirección predeterminada')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de Envío',
                'verbose_name_plural': 'Direcciones de Envío',
                'ordering': ['-predetermina', '-creado'],
            },
        ),
    ]
