# Generated by Django 5.2.6 on 2026-05-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_direccionenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(choices=[('original', 'Original'), ('primavera', 'Primavera'), ('verano', 'Verano'), ('otono', 'Otoño'), ('invierno', 'Invierno')], default='original', max_length=20, verbose_name='Temporada activa')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Temporada',
                'verbose_name_plural': 'Configuraciones de Temporada',
            },
        ),
    ]
