# Generated by Django 5.2.6 on 2026-06-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_configuraciontemporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='tamano',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_grande',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio para el tamaño grande del producto. Dejar vacío si solo hay un tamaño.', max_digits=8, null=True, verbose_name='Precio Grande (Opcional)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_grande',
            field=models.PositiveIntegerField(default=0, help_text='Número de unidades de tamaño grande disponibles en inventario.', verbose_name='Stock Grande (Opcional)'),
        ),
    ]
