# Generated by Django 5.2.6 on 2026-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_ordenitem_tamano_producto_precio_grande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento para el producto en ofertas especiales (ej. 15 para 15% OFF). Deja en 0 para sin descuento.', verbose_name='Descuento (%)'),
        ),
    ]
