# Generated by Django 5.2.6 on 2026-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_producto_descuento_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
    ]
