# Generated by Django 5.2.6 on 2026-06-08 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_orden_costo_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento aplicado'),
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Cupón')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto Fijo'), ('envio_gratis', 'Envío Gratis')], default='porcentaje', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje (ej. 10 para 10%) o Monto (ej. 50 para $50)', max_digits=10)),
                ('compra_minima', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra (subtotal) para aplicar el cupón', max_digits=10)),
                ('valido_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('valido_hasta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('limite_usos', models.IntegerField(default=0, help_text='0 significa sin límite')),
                ('usos_actuales', models.IntegerField(default=0)),
                ('usuario_asignado', models.ForeignKey(blank=True, help_text='Opcional. Limitar uso a este usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='catalogo.cupon'),
        ),
    ]
