# Generated by Django 5.2.6 on 2026-06-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_orden_descuento_aplicado_cupon_orden_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino (Nuestras...)'), ('masculino', 'Masculino (Nuestros...)')], default='femenino', help_text='Determina el artículo que se usará en el catálogo: Nuestras Galletas / Nuestros Roles', max_length=10),
        ),
    ]
